services:
    phpbb.skeleton.command.create:
        class: phpbb\skeleton\console\create
        arguments:
            - '@user'
            - '@language'
            - '@phpbb.skeleton.helper.packager'
            - '@phpbb.skeleton.helper.validator'
        tags:
            - { name: console.command }
